name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Automation Exercise Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g allure-commandline
          
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js

      - name: Generate Allure Report
        if: always()
        run: |
          npm run allure:clear
          npm run allure:generate

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report 
          path: allure-report/
          retention-days: 30
          if-no-files-found: error # New feature in v4
          compression-level: 6 # New feature in v4 to optimize upload size